@startmindmap
*[#Orange] Treasurer
** Кошелек
*** CRUD кошелька
*** Сохранение данных о поступленииях денег
*** Сохранение данных о тратах
*** Отчет о движениях денег
** Категории трат
*** CRUD для категорий
*** Привязка транзакций к категориям
** Авторизация
*** Работа с JWT токенами
*** Ролевая система доступа к данным
*** Добавление других пользователей
*** Аудит действий в системе
** Телеграм бот для работы с данными
** Визуализация действий при помощи шаблонизатора ThymeLeaf
*** Для каждого раздела API используем шаблонизатор для вывода в браузере
@endmindmap